---

- name: stoping bot
  command:
    cmd: "sudo systemctl stop webmtogif"
  ignore_errors: yes

- name: remove current version
  file:
    path: "{{ application_path }}"
    state: absent
  become: yes

- name: Create user
  ansible.builtin.user:
    name: telegram-bot

- name: copy bot files
  copy:
    src: "app/"
    dest: "{{ application_path }}"
  become: yes
  become_user: telegram-bot

- name: creating virtual environment
  command:
    cmd: "{{ ansible_python_interpreter }} -m venv {{ application_path }}"
  become: yes
  become_user: telegram-bot

- name: install depences
  command:
    cmd: "{{ application_path }}/bin/pip install -r {{ application_path }}/requirements.txt"
  become: yes
  become_user: telegram-bot

- name: create config dir
  file:
    state: directory
    path: "{{ application_path }}/config/"
  become: yes
  become_user: telegram-bot

- name: create config
  template:
    src: config.yml.j2
    dest: "{{ application_path }}/config/config.yml"
    owner: telegram-bot
    group: telegram-bot
  become: yes
  become_user: telegram-bot

- name: create files dir
  file:
    state: directory
    path: "{{ application_path }}/files/"
  become: yes
  become_user: telegram-bot

- name: create syslog unit
  template:
    src: webmtogif.service.j2
    dest: "/etc/systemd/system/webmtogif.service"
    owner: root
    group: root
  ignore_errors: yes
  become: yes

- name: starting bot
  command:
    cmd: "sudo systemctl start webmtogif"
